/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/quick-start',
      ],
    },
    {
      type: 'category',
      label: 'Tenants',
      items: [
        'tenants/tenant-management',
      ],
    },
    {
      type: 'category',
      label: 'Helm Charts',
      items: [
        'helm/overview',
        'helm/multi-container-setup',
      ],
    },
    {
      type: 'category',
      label: 'ArgoCD',
      items: [
        'argocd/setup',
        'argocd/aims-core-application',
      ],
    },
    {
      type: 'category',
      label: 'CI/CD',
      items: [
        'ci-cd/workflows',
      ],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      items: [
        {
          type: 'autogenerated',
          dirName: 'infrastructure',
        },
      ],
    },
  ],
};

export default sidebars;
